export type Errors =
  | "core/internal_server_error"
  | "core/not_implemented"
  | "storage/file_not_exist"
  | "storage/permission_denied"
  | "common/wrong_arguments"
  | "common/file_missing"
  | "user/not_exist"
  | "user/exist"
  | "user/login_required"
  | "user/logout_required"
  | "user/password_wrong"
  | "user/invalid_username"
  | "user/file_exists"
  | "user/file_not_found"
  | "user/session_not_found"
  | "user/permission_denied";
